# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    open-pull-requests-limit: 0
    schedule:
      interval: "daily"
      time: "08:45"
    commit-message:
      prefix: "build(npm):"
    groups:
      minor:
        update-types: ["minor", "patch"]
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
